/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IComputeManager } from "./IComputeManager";
export type { IComputeRequestManager } from "./IComputeRequestManager";
export type { IMemoryTree } from "./IMemoryTree";
export type { IPayment } from "./IPayment";
