/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721AQueryable } from "./ERC721AQueryable";
export type { IERC721AQueryable } from "./IERC721AQueryable";
