/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721ASol from "./ERC721A.sol";
export type { erc721ASol };
import type * as extensions from "./extensions";
export type { extensions };
export type { IERC721A } from "./IERC721A";
