[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"

optimizer = true
optimizer-runs = 200

[rpc_endpoints]
root = "${ROOT_RPC_URL}"
porcini = "${PORCINI_RPC_URL}"
seed = "${SEED_ROOT_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "single"
wrap_comments = false
override_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
